In [1]:
import pandas as pd

df = pd.read_csv("Source 1.csv")
print(df.shape)
print(df.columns)
df.head()

(1925, 11)
Index(['video_id', 'url', 'title', 'channel', 'category', 'duration_seconds',
       'duration_minutes', 'view_count', 'like_count', 'comment_count',
       'published_at'],
      dtype='object')

,video_id,url,title,channel,category,duration_seconds,duration_minutes,view_count,like_count,comment_count,published_at
0,_uQrJ0TkZlc,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,Programming with Mosh,python tutorial,22447,374.12,46484976,1226186,61315,2019-02-18T15:00:08Z
1,kqtD5dpn9C8,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,Programming with Mosh,python tutorial,3606,60.10,23266146,532774,26625,2020-09-16T13:00:20Z
2,rfscVS0vtbw,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,freeCodeCamp.org,python tutorial,16012,266.87,48131277,1109421,45939,2018-07-11T18:00:42Z
3,t8pPdKYpowI,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,TechWorld with Nana,python tutorial,19890,331.50,6599656,167519,4008,2021-03-05T14:10:17Z
4,K5KVEU3aaeQ,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],Programming with Mosh,python tutorial,7341,122.35,4613318,112457,3020,2025-02-12T12:30:31Z

In [45]:
columns_to_drop = ['video_id', 'channel', 'duration_minutes', 'published_at']  #only used columns are kept
df = df.drop(columns=columns_to_drop)
print("Columns after removal:")
print(df.columns.tolist())
print(f"\nNew shape: {df.shape}")

Columns after removal:
['url', 'title', 'category', 'duration_seconds', 'view_count', 'like_count', 'comment_count']

New shape: (1925, 7)

In [46]:
df

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,python tutorial,22447,46484976,1226186,61315
1,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,python tutorial,3606,23266146,532774,26625
2,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,python tutorial,16012,48131277,1109421,45939
3,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,python tutorial,19890,6599656,167519,4008
4,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],python tutorial,7341,4613318,112457,3020
...,...,...,...,...,...,...,...
1920,https://www.youtube.com/watch?v=4jrk81foQx8,"PACK, PREP AND TRAVEL W ME TO HAWAII FOR A MON...",travelling,1014,111869,3228,80
1921,https://www.youtube.com/watch?v=XsghWAjUKuU,Malaysia Kuala Lumpur 🇲🇾 #travel #viralvideo #...,travelling,8,1910,0,0
1922,https://www.youtube.com/watch?v=e7pkte-fuOU,Wonders of Greece | Most Amazing Places in Gre...,travelling,3607,439933,3143,132
1923,https://www.youtube.com/watch?v=x_ywByCJ0hk,Things to BEWARE OF IN SOUTH KOREA 😬 #travel #...,travelling,60,368443,5535,594
1924,https://www.youtube.com/watch?v=_yhshdwPnEg,Solo Travelling is so boaring 🥹 #Shorts #trave...,travelling,55,16724388,533002,464

In [47]:
print(df.isnull().sum())  #chek if there is any empty values

url                 0
title               0
category            0
duration_seconds    0
view_count          0
like_count          0
comment_count       0
dtype: int64

In [48]:
print(f"Before: {len(df)}")
df = df.drop_duplicates(subset=['url'], keep='first')  #drop duplicates (same rows with same values)
print(f"After: {len(df)}")

Before: 1925
After: 1819

In [49]:
df

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,python tutorial,22447,46484976,1226186,61315
1,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,python tutorial,3606,23266146,532774,26625
2,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,python tutorial,16012,48131277,1109421,45939
3,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,python tutorial,19890,6599656,167519,4008
4,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],python tutorial,7341,4613318,112457,3020
...,...,...,...,...,...,...,...
1920,https://www.youtube.com/watch?v=4jrk81foQx8,"PACK, PREP AND TRAVEL W ME TO HAWAII FOR A MON...",travelling,1014,111869,3228,80
1921,https://www.youtube.com/watch?v=XsghWAjUKuU,Malaysia Kuala Lumpur 🇲🇾 #travel #viralvideo #...,travelling,8,1910,0,0
1922,https://www.youtube.com/watch?v=e7pkte-fuOU,Wonders of Greece | Most Amazing Places in Gre...,travelling,3607,439933,3143,132
1923,https://www.youtube.com/watch?v=x_ywByCJ0hk,Things to BEWARE OF IN SOUTH KOREA 😬 #travel #...,travelling,60,368443,5535,594
1924,https://www.youtube.com/watch?v=_yhshdwPnEg,Solo Travelling is so boaring 🥹 #Shorts #trave...,travelling,55,16724388,533002,464

In [ ]:
df.to_csv('Source 1 CLEANED.csv', index=False)  #prevent saving index as a column

In [ ]:
print(f"Original rows: {len(df)}")

df = df[(df['like_count'] <= df['view_count']) & 
        (df['comment_count'] <= df['view_count'])]
 #if number of likes or comments is greater than views ->impossible values
print(f"After removing impossible values: {len(df)}")

min_ratio = 0.0001 #as the youtube average ratio is 0.01 so 0.0001 (which is applied) is very suspicious 
df = df[
    ((df['like_count'] / df['view_count']) >= min_ratio) |
    ((df['comment_count'] / df['view_count']) >= min_ratio)
]
 #if number of likes or comments doesn't reach the minimum ratio then it is removed
print(f"After removing suspicious low engagement: {len(df)}")

df.to_csv("Source 1 CLEANED.csv", index=False)

Original rows: 1819
After removing impossible values: 1819
After removing suspicious low engagement: 1742

In [ ]:
df.to_csv('Source 1 CLEANED.csv', index=False)

In [34]:
print(df.dtypes)
print("\n")
print(df.info()) #making sure that all data types are correct

url                 object
title               object
category            object
duration_seconds     int64
view_count           int64
like_count           int64
comment_count        int64
dtype: object


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1846 entries, 0 to 1845
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   url               1846 non-null   object
 1   title             1846 non-null   object
 2   category          1846 non-null   object
 3   duration_seconds  1846 non-null   int64
 4   view_count        1846 non-null   int64
 5   like_count        1846 non-null   int64
 6   comment_count     1846 non-null   int64
dtypes: int64(4), object(3)
memory usage: 101.1+ KB
None