In [25]:
import pandas as pd

In [26]:
df1 = pd.read_csv("cleanedData.csv")
df1.head()

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,python tutorial,22447,46484976,1226186,61315
1,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,python tutorial,3606,23266146,532774,26625
2,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,python tutorial,16012,48131277,1109421,45939
3,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,python tutorial,19890,6599656,167519,4008
4,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],python tutorial,7341,4613318,112457,3020

In [29]:
df2 = pd.read_csv("top_600_youtube_videos_2023.csv")
df2.head()

,title,duration,view_count,like_count,comment_count,duration_seconds
0,Let's see if you dare next time #Shorts #017,PT18S,246200629,1572774.0,942.0,18.0
1,[6번] 식당 업소용 음식포장 비닐랩 절단기,PT15S,160984366,1472323.0,678.0,15.0
2,Khaby Lame react epic moments #shorts #kabhylame,PT19S,96455747,2312319.0,2203.0,19.0
3,Polina Knoroz's Cute Moment in Sports #shorts,PT35S,91902366,1397067.0,930.0,35.0
4,Salute to indian army🇮🇳❤️💯 #army #trending #vi...,PT30S,85157682,1973374.0,0.0,30.0

In [30]:
# Add placeholders for missing columns in df2
df2['url'] = 'No URL'
df2['category'] = 'Unknown'

# Check first 5 rows of df2
print(df2.head())

                                               title duration  view_count  \
0       Let's see if you dare next time #Shorts #017    PT18S   246200629
1                           [6번] 식당 업소용 음식포장 비닐랩 절단기    PT15S   160984366
2   Khaby Lame react epic moments #shorts #kabhylame    PT19S    96455747
3      Polina Knoroz's Cute Moment in Sports #shorts    PT35S    91902366
4  Salute to indian army🇮🇳❤️💯 #army #trending #vi...    PT30S    85157682

   like_count  comment_count  duration_seconds     url category
0   1572774.0          942.0              18.0  No URL  Unknown
1   1472323.0          678.0              15.0  No URL  Unknown
2   2312319.0         2203.0              19.0  No URL  Unknown
3   1397067.0          930.0              35.0  No URL  Unknown
4   1973374.0            0.0              30.0  No URL  Unknown

In [31]:
# Make sure df2 columns are in the same order as df1
df2 = df2[df1.columns]

# Check columns
print(df2.columns)

Index(['url', 'title', 'category', 'duration_seconds', 'view_count',
       'like_count', 'comment_count'],
      dtype='object')

In [37]:
# Stack df2 below df1
df = pd.concat([df1, df2], ignore_index=True)

# Check first 10 rows
print(integrated_df.head(10))

                                           url  \
0  https://www.youtube.com/watch?v=_uQrJ0TkZlc
1  https://www.youtube.com/watch?v=kqtD5dpn9C8
2  https://www.youtube.com/watch?v=rfscVS0vtbw
3  https://www.youtube.com/watch?v=t8pPdKYpowI
4  https://www.youtube.com/watch?v=K5KVEU3aaeQ
5  https://www.youtube.com/watch?v=Z1Yd7upQsXY
6  https://www.youtube.com/watch?v=b093aqAZiPU
7  https://www.youtube.com/watch?v=qwAFL1597eM
8  https://www.youtube.com/watch?v=nluUYtejoIE
9  https://www.youtube.com/watch?v=fWjsdhR3z3c

                                               title         category  \
0                   Python Full Course for Beginners  python tutorial
1  Python for Beginners - Learn Coding with Pytho...  python tutorial
2  Learn Python - Full Course for Beginners [Tuto...  python tutorial
3  Python Tutorial for Beginners - Learn Python i...  python tutorial
4            Python Full Course for Beginners [2025]  python tutorial
5  Python Tutorial for Absolute Beginners #1 - Wh...  python tutorial
6                  👩‍💻 Python for Beginners Tutorial  python tutorial
7  Python Tutorial for Beginners (with mini-proje...  python tutorial
8  Python Basics: Your FIRST Program in Under a M...  python tutorial
9  Learn Python in Less than 10 Minutes for Begin...  python tutorial

   duration_seconds  view_count  like_count  comment_count
0           22447.0    46484976   1226186.0        61315.0
1            3606.0    23266146    532774.0        26625.0
2           16012.0    48131277   1109421.0        45939.0
3           19890.0     6599656    167519.0         4008.0
4            7341.0     4613318    112457.0         3020.0
5            1478.0     9375185    203512.0         8571.0
6            3801.0     4159842     90575.0         3079.0
7           31314.0      993222     20712.0          615.0
8              25.0      745778     10707.0           96.0
9             630.0     1142001     26536.0          670.0

In [38]:

df = integrated_df.drop_duplicates()

Integrated dataset saved to 'integrated_data.csv'

In [35]:
integrated_df

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,python tutorial,22447.0,46484976,1226186.0,61315.0
1,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,python tutorial,3606.0,23266146,532774.0,26625.0
2,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,python tutorial,16012.0,48131277,1109421.0,45939.0
3,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,python tutorial,19890.0,6599656,167519.0,4008.0
4,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],python tutorial,7341.0,4613318,112457.0,3020.0
...,...,...,...,...,...,...,...
2338,No URL,White People Hate Black Hair?,Unknown,60.0,99052,11291.0,1210.0
2339,No URL,Biden White House is 'stonewalling' this inves...,Unknown,327.0,94648,2690.0,964.0
2340,No URL,[다시보기] 백현동 발언 허위라도…ㅣ2023년 12월 11일 김진의 더라방,Unknown,2569.0,93376,7401.0,169.0
2341,No URL,[2023년 12월 11일 월요일 오전 8시 생방송] 김기현 거취 결단 요구 봇물,Unknown,10619.0,89526,15254.0,152.0
2342,No URL,✅ MISA DE HOY lunes 11 de Diciembre 2023 - Pad...,Unknown,3710.0,113137,23035.0,761.0

In [39]:
df.isna().sum()

url                  0
title                0
category             0
duration_seconds     4
view_count           0
like_count           3
comment_count       11
dtype: int64

In [40]:
df['duration_seconds'] = df['duration_seconds'].fillna(df['duration_seconds'].median())
df['comment_count'] = df['comment_count'].fillna(df['comment_count'].median())
df['like_count'] = df['like_count'].fillna(df['like_count'].median())

In [41]:
df.isna().sum()

url                 0
title               0
category            0
duration_seconds    0
view_count          0
like_count          0
comment_count       0
dtype: int64

In [42]:
df.info

<bound method DataFrame.info of                                               url  \
0     https://www.youtube.com/watch?v=_uQrJ0TkZlc
1     https://www.youtube.com/watch?v=kqtD5dpn9C8
2     https://www.youtube.com/watch?v=rfscVS0vtbw
3     https://www.youtube.com/watch?v=t8pPdKYpowI
4     https://www.youtube.com/watch?v=K5KVEU3aaeQ
...                                           ...
2338                                       No URL
2339                                       No URL
2340                                       No URL
2341                                       No URL
2342                                       No URL

                                                  title         category  \
0                      Python Full Course for Beginners  python tutorial
1     Python for Beginners - Learn Coding with Pytho...  python tutorial
2     Learn Python - Full Course for Beginners [Tuto...  python tutorial
3     Python Tutorial for Beginners - Learn Python i...  python tutorial
4               Python Full Course for Beginners [2025]  python tutorial
...                                                 ...              ...
2338                      White People Hate Black Hair?          Unknown
2339  Biden White House is 'stonewalling' this inves...          Unknown
2340          [다시보기] 백현동 발언 허위라도…ㅣ2023년 12월 11일 김진의 더라방          Unknown
2341      [2023년 12월 11일 월요일 오전 8시 생방송] 김기현 거취 결단 요구 봇물          Unknown
2342  ✅ MISA DE HOY lunes 11 de Diciembre 2023 - Pad...          Unknown

      duration_seconds  view_count  like_count  comment_count
0              22447.0    46484976   1226186.0        61315.0
1               3606.0    23266146    532774.0        26625.0
2              16012.0    48131277   1109421.0        45939.0
3              19890.0     6599656    167519.0         4008.0
4               7341.0     4613318    112457.0         3020.0
...                ...         ...         ...            ...
2338              60.0       99052     11291.0         1210.0
2339             327.0       94648      2690.0          964.0
2340            2569.0       93376      7401.0          169.0
2341           10619.0       89526     15254.0          152.0
2342            3710.0      113137     23035.0          761.0

[2222 rows x 7 columns]>

In [44]:
df.head(5)

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=_uQrJ0TkZlc,Python Full Course for Beginners,python tutorial,22447.0,46484976,1226186.0,61315.0
1,https://www.youtube.com/watch?v=kqtD5dpn9C8,Python for Beginners - Learn Coding with Pytho...,python tutorial,3606.0,23266146,532774.0,26625.0
2,https://www.youtube.com/watch?v=rfscVS0vtbw,Learn Python - Full Course for Beginners [Tuto...,python tutorial,16012.0,48131277,1109421.0,45939.0
3,https://www.youtube.com/watch?v=t8pPdKYpowI,Python Tutorial for Beginners - Learn Python i...,python tutorial,19890.0,6599656,167519.0,4008.0
4,https://www.youtube.com/watch?v=K5KVEU3aaeQ,Python Full Course for Beginners [2025],python tutorial,7341.0,4613318,112457.0,3020.0

In [46]:
# Save to CSV
df.to_csv('integrateddd_data.csv', index=False)


print("Integrated dataset saved to 'integrateddd_data.csv'")

Integrated dataset saved to 'integrateddd_data.csv'