In [1]:
import pandas as pd

In [5]:
df1 = pd.read_csv("tiktok_cleaned.csv")
df1.head()

,username,likes,comments,shares,views,duration_seconds,created_at,url,engagement_rate,date
0,661._miaa,183900,329,3361,826700,9,2024-09-16 17:56:17+00:00,https://www.tiktok.com/@661._miaa/video/741530...,0.226914,2024-09-16
1,chasityromann,236600,379,5518,2600000,15,2024-06-03 22:22:38+00:00,https://www.tiktok.com/@chasityromann/video/73...,0.093268,2024-06-03
2,lindceybeautyy,404000,936,9560,3200000,12,2024-08-04 14:26:09+00:00,https://www.tiktok.com/@lindceybeautyy/video/7...,0.129530,2024-08-04
3,iannelsonnnnn,359300,936,11700,3500000,15,2024-05-28 21:38:48+00:00,https://www.tiktok.com/@iannelsonnnnn/video/73...,0.106267,2024-05-28
4,nightmoonxyz,2391,99,118,48600,21,2025-04-23 04:25:50+00:00,https://www.tiktok.com/@nightmoonxyz/video/749...,0.053663,2025-04-23

In [7]:
df2 = pd.read_csv("tiktok_source2_clean_aligned.csv")
df2.head()

,videoId,videoUrl,text,hashtag,createTime,likes,comments,shares,views,authorUsername,authorName
0,6862153058223197445,https://www.tiktok.com/@/video/686215305822319...,To the 🐝 🐝 🐝 #fyp,fyp,2020-08-18 02:58:41,72392654,2800855,42489319,889198466,bellapoarch,Bella Poarch
1,6911406868699073798,https://www.tiktok.com/@/video/691140686869907...,😳This is one of my best drawings #dlaciebie #t...,fyp,2020-12-28 20:28:43,52117039,758413,1032348,308104412,franekbielak_art,Franek Bielak
2,7298305522623679752,https://www.tiktok.com/@/video/729830552262367...,🤍🤍 #foryou #fyp #teacher #school #suprise #for...,fyp,2023-11-06 11:12:57,51037805,257879,773108,402493327,metrevelisalii,Salome
3,7523242837467598102,https://www.tiktok.com/@/video/752324283746759...,Appreciating those views😮‍💨 #jet2holidays #fyp...,fyp,2025-07-04 15:04:36,42180875,196827,9259038,343454666,bben9450,BradBen
4,7028775404173413678,https://www.tiktok.com/@/video/702877540417341...,bruh this shit has me WHEEZING #fyp,fyp,2021-11-10 03:18:23,40897424,492158,1973949,251230665,adrianchateau,Adrian Chateau Wiles

In [8]:
df2.rename(columns={'authorUsername': 'username'}, inplace=True)

In [9]:
df1['created_at'] = pd.to_datetime(df1['created_at'])
df2['createTime'] = pd.to_datetime(df2['createTime'])

In [10]:
df2.rename(columns={'createTime': 'created_at'}, inplace=True)

In [11]:
df2['engagement_rate'] = (
    (df2['likes'] + df2['comments'] + df2['shares']) / df2['views']
)

In [12]:
df2 = df2[df2['views'] > 0]
# handle zero views

In [13]:
df1_clean = df1[[
    'username', 'created_at', 'likes',
    'comments', 'shares', 'views', 'engagement_rate'
]]

df2_clean = df2[[
    'username', 'created_at', 'likes',
    'comments', 'shares', 'views', 'engagement_rate'
]]

In [14]:
df = pd.concat([df1_clean, df2_clean], ignore_index=True)

In [15]:
df

,username,created_at,likes,comments,shares,views,engagement_rate
0,661._miaa,2024-09-16 17:56:17+00:00,183900,329,3361,826700,0.226914
1,chasityromann,2024-06-03 22:22:38+00:00,236600,379,5518,2600000,0.093268
2,lindceybeautyy,2024-08-04 14:26:09+00:00,404000,936,9560,3200000,0.129530
3,iannelsonnnnn,2024-05-28 21:38:48+00:00,359300,936,11700,3500000,0.106267
4,nightmoonxyz,2025-04-23 04:25:50+00:00,2391,99,118,48600,0.053663
...,...,...,...,...,...,...,...
2622,juliachaves_ofc,2024-04-28 22:40:27,6662795,35074,110429,49994660,0.136181
2623,juliaglowala,2025-01-30 17:58:54,6658552,27726,557786,45059676,0.160766
2624,asadkhan_31,2019-11-29 12:43:19,6657884,10891,137463,65777308,0.103474
2625,grandpajordan99,2024-12-21 21:05:43,6649163,35678,552265,50545470,0.143180
2626,jaqueline.soaress,2023-08-05 14:03:11,6635931,72265,820703,51730871,0.145540

In [24]:
df = df.dropna(subset=['created_at']) 
# drop invaliddd dates

In [28]:
df = df.copy()
df['post_date'] = df['created_at'].dt.date

In [31]:
df

,username,created_at,likes,comments,shares,views,engagement_rate,post_date
0,661._miaa,2024-09-16 17:56:17+00:00,183900,329,3361,826700,0.226914,2024-09-16
1,chasityromann,2024-06-03 22:22:38+00:00,236600,379,5518,2600000,0.093268,2024-06-03
2,lindceybeautyy,2024-08-04 14:26:09+00:00,404000,936,9560,3200000,0.129530,2024-08-04
3,iannelsonnnnn,2024-05-28 21:38:48+00:00,359300,936,11700,3500000,0.106267,2024-05-28
4,nightmoonxyz,2025-04-23 04:25:50+00:00,2391,99,118,48600,0.053663,2025-04-23
...,...,...,...,...,...,...,...,...
1205,geograpyh.geniuse,2025-02-08 10:27:18+00:00,83100,321,1459,3400000,0.024965,2025-02-08
1206,evimawete,2025-12-24 17:04:50+00:00,292,12,7,2846,0.109276,2025-12-24
1207,brookemonk_,2024-02-24 21:32:23+00:00,6900000,8822,7165,74900000,0.092336,2024-02-24
1208,bruhwutisthis_0,2024-11-24 23:11:49+00:00,307700,1500,14000,1300000,0.248615,2024-11-24
1209,dareksoul,2024-07-05 15:05:52+00:00,92000,325,1499,3400000,0.027595,2024-07-05

In [45]:
df

,username,created_at,likes,comments,shares,views,engagement_rate,post_date
0,661._miaa,2024-09-16 17:56:17+00:00,183900,329,3361,826700,0.226914,2024-09-16
1,chasityromann,2024-06-03 22:22:38+00:00,236600,379,5518,2600000,0.093268,2024-06-03
2,lindceybeautyy,2024-08-04 14:26:09+00:00,404000,936,9560,3200000,0.129530,2024-08-04
3,iannelsonnnnn,2024-05-28 21:38:48+00:00,359300,936,11700,3500000,0.106267,2024-05-28
4,nightmoonxyz,2025-04-23 04:25:50+00:00,2391,99,118,48600,0.053663,2025-04-23
...,...,...,...,...,...,...,...,...
1205,geograpyh.geniuse,2025-02-08 10:27:18+00:00,83100,321,1459,3400000,0.024965,2025-02-08
1206,evimawete,2025-12-24 17:04:50+00:00,292,12,7,2846,0.109276,2025-12-24
1207,brookemonk_,2024-02-24 21:32:23+00:00,6900000,8822,7165,74900000,0.092336,2024-02-24
1208,bruhwutisthis_0,2024-11-24 23:11:49+00:00,307700,1500,14000,1300000,0.248615,2024-11-24
1209,dareksoul,2024-07-05 15:05:52+00:00,92000,325,1499,3400000,0.027595,2024-07-05

In [57]:
# Count how many videos each user posted that day and add as a new column
df['posts_per_day'] = df.groupby(['username', 'post_date'])['post_date'].transform('count')

# Now each video row has the posting frequency for that day
print(df[['username', 'post_date', 'posts_per_day', 'engagement_rate']].head())

         username   post_date  posts_per_day  engagement_rate
0       661._miaa  2024-09-16              1         0.226914
1   chasityromann  2024-06-03              1         0.093268
2  lindceybeautyy  2024-08-04              1         0.129530
3   iannelsonnnnn  2024-05-28              1         0.106267
4    nightmoonxyz  2025-04-23              1         0.053663

In [58]:
df

,username,created_at,likes,comments,shares,views,engagement_rate,post_date,posts_per_day
0,661._miaa,2024-09-16 17:56:17+00:00,183900,329,3361,826700,0.226914,2024-09-16,1
1,chasityromann,2024-06-03 22:22:38+00:00,236600,379,5518,2600000,0.093268,2024-06-03,1
2,lindceybeautyy,2024-08-04 14:26:09+00:00,404000,936,9560,3200000,0.129530,2024-08-04,1
3,iannelsonnnnn,2024-05-28 21:38:48+00:00,359300,936,11700,3500000,0.106267,2024-05-28,1
4,nightmoonxyz,2025-04-23 04:25:50+00:00,2391,99,118,48600,0.053663,2025-04-23,1
...,...,...,...,...,...,...,...,...,...
1205,geograpyh.geniuse,2025-02-08 10:27:18+00:00,83100,321,1459,3400000,0.024965,2025-02-08,1
1206,evimawete,2025-12-24 17:04:50+00:00,292,12,7,2846,0.109276,2025-12-24,1
1207,brookemonk_,2024-02-24 21:32:23+00:00,6900000,8822,7165,74900000,0.092336,2024-02-24,1
1208,bruhwutisthis_0,2024-11-24 23:11:49+00:00,307700,1500,14000,1300000,0.248615,2024-11-24,1
1209,dareksoul,2024-07-05 15:05:52+00:00,92000,325,1499,3400000,0.027595,2024-07-05,1

In [59]:
# Average engagement rate by posting frequency
avg_engagement = df.groupby('posts_per_day')['engagement_rate'].mean()
print(avg_engagement)
# so we see  the low engagement_rate for post twice per day

posts_per_day
1    0.116960
2    0.070040
3    0.101812
Name: engagement_rate, dtype: float64

In [60]:
df

,username,created_at,likes,comments,shares,views,engagement_rate,post_date,posts_per_day
0,661._miaa,2024-09-16 17:56:17+00:00,183900,329,3361,826700,0.226914,2024-09-16,1
1,chasityromann,2024-06-03 22:22:38+00:00,236600,379,5518,2600000,0.093268,2024-06-03,1
2,lindceybeautyy,2024-08-04 14:26:09+00:00,404000,936,9560,3200000,0.129530,2024-08-04,1
3,iannelsonnnnn,2024-05-28 21:38:48+00:00,359300,936,11700,3500000,0.106267,2024-05-28,1
4,nightmoonxyz,2025-04-23 04:25:50+00:00,2391,99,118,48600,0.053663,2025-04-23,1
...,...,...,...,...,...,...,...,...,...
1205,geograpyh.geniuse,2025-02-08 10:27:18+00:00,83100,321,1459,3400000,0.024965,2025-02-08,1
1206,evimawete,2025-12-24 17:04:50+00:00,292,12,7,2846,0.109276,2025-12-24,1
1207,brookemonk_,2024-02-24 21:32:23+00:00,6900000,8822,7165,74900000,0.092336,2024-02-24,1
1208,bruhwutisthis_0,2024-11-24 23:11:49+00:00,307700,1500,14000,1300000,0.248615,2024-11-24,1
1209,dareksoul,2024-07-05 15:05:52+00:00,92000,325,1499,3400000,0.027595,2024-07-05,1

In [61]:
df.to_csv('Final Integrated data for second question', index=False)


print("Final Integrated data for second question'")

Final Integrated data for second question'