In [1]:
import pandas as pd

In [23]:
df1 = pd.read_csv("Integrated-Data-Final-STRATIFIED_1500.csv")
df1.head()

,url,title,category,duration_seconds,view_count,like_count,comment_count,duration_bucket
0,https://www.youtube.com/watch?v=Di9oaC1lDJI,Creative Flower Photography with Phone📱 🔥| Pho...,photography tutorials,13,620112,14371,54,<=60
1,https://www.youtube.com/watch?v=h0FLvJxRU6w,How to Learn The Basics of Christianity Withou...,religious content,20,361355,17500,783,<=60
2,https://www.youtube.com/watch?v=wPCQVwh6BiA,Travel Photography Tip 📲,photography tutorials,43,40748489,2903165,12652,<=60
3,https://www.youtube.com/watch?v=OekdUrh4Sjg,Travel with me✈️! #travel #facemask #vlog #mak...,travelling,36,4904533,101047,580,<=60
4,https://www.youtube.com/watch?v=NKHi12DMcC4,How to survive college #cooking #food #foodasm...,food recipes,38,7665699,0,1422,<=60

In [24]:
df2 = pd.read_csv("yt-long-vids-cleaned.csv")
df2.head()

,url,title,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=QYbmomFCwPI,Apocalypto part 2 Full Movie (2025) #apocalypse,5780,7332,109,1
1,https://www.youtube.com/watch?v=IDfsTZV-sq0,How to be Happy Alone? | Daily English Convers...,1201,5472,248,15
2,https://www.youtube.com/watch?v=vqG0uLBlNmY,Kaya Turns Inside Out | The Official Podcast,4074,6565,279,94
3,https://www.youtube.com/watch?v=kaUemcqIQ-k,"United States of Secrets, Part One (full docum...",6798,10252895,81201,8687
4,https://www.youtube.com/watch?v=DNJJjhfBshk,"273. ""Chrimbo 4 Bimbo's"" | The Pull Up Podcast",6309,2953,207,38

In [25]:
# df1 = df1.drop(columns=['duration_bucket'])
df2['category'] = 'Unknown'

print(df2.head())
print(df1.head())

                                           url  \
0  https://www.youtube.com/watch?v=QYbmomFCwPI
1  https://www.youtube.com/watch?v=IDfsTZV-sq0
2  https://www.youtube.com/watch?v=vqG0uLBlNmY
3  https://www.youtube.com/watch?v=kaUemcqIQ-k
4  https://www.youtube.com/watch?v=DNJJjhfBshk

                                               title  duration_seconds  \
0    Apocalypto part 2 Full Movie (2025) #apocalypse              5780
1  How to be Happy Alone? | Daily English Convers...              1201
2       Kaya Turns Inside Out | The Official Podcast              4074
3  United States of Secrets, Part One (full docum...              6798
4     273. "Chrimbo 4 Bimbo's" | The Pull Up Podcast              6309

   view_count  like_count  comment_count category
0        7332         109              1  Unknown
1        5472         248             15  Unknown
2        6565         279             94  Unknown
3    10252895       81201           8687  Unknown
4        2953         207             38  Unknown
                                           url  \
0  https://www.youtube.com/watch?v=Di9oaC1lDJI
1  https://www.youtube.com/watch?v=h0FLvJxRU6w
2  https://www.youtube.com/watch?v=wPCQVwh6BiA
3  https://www.youtube.com/watch?v=OekdUrh4Sjg
4  https://www.youtube.com/watch?v=NKHi12DMcC4

                                               title               category  \
0  Creative Flower Photography with Phone📱 🔥| Pho...  photography tutorials
1  How to Learn The Basics of Christianity Withou...      religious content
2                           Travel Photography Tip 📲  photography tutorials
3  Travel with me✈️! #travel #facemask #vlog #mak...             travelling
4  How to survive college #cooking #food #foodasm...           food recipes

   duration_seconds  view_count  like_count  comment_count duration_bucket
0                13      620112       14371             54            <=60
1                20      361355       17500            783            <=60
2                43    40748489     2903165          12652            <=60
3                36     4904533      101047            580            <=60
4                38     7665699           0           1422            <=60

In [26]:
print(df1.head())

                                           url  \
0  https://www.youtube.com/watch?v=Di9oaC1lDJI
1  https://www.youtube.com/watch?v=h0FLvJxRU6w
2  https://www.youtube.com/watch?v=wPCQVwh6BiA
3  https://www.youtube.com/watch?v=OekdUrh4Sjg
4  https://www.youtube.com/watch?v=NKHi12DMcC4

                                               title               category  \
0  Creative Flower Photography with Phone📱 🔥| Pho...  photography tutorials
1  How to Learn The Basics of Christianity Withou...      religious content
2                           Travel Photography Tip 📲  photography tutorials
3  Travel with me✈️! #travel #facemask #vlog #mak...             travelling
4  How to survive college #cooking #food #foodasm...           food recipes

   duration_seconds  view_count  like_count  comment_count duration_bucket
0                13      620112       14371             54            <=60
1                20      361355       17500            783            <=60
2                43    40748489     2903165          12652            <=60
3                36     4904533      101047            580            <=60
4                38     7665699           0           1422            <=60

In [27]:
df1 = df1.drop(columns=['duration_bucket'])

In [28]:
print(df1.head())

                                           url  \
0  https://www.youtube.com/watch?v=Di9oaC1lDJI
1  https://www.youtube.com/watch?v=h0FLvJxRU6w
2  https://www.youtube.com/watch?v=wPCQVwh6BiA
3  https://www.youtube.com/watch?v=OekdUrh4Sjg
4  https://www.youtube.com/watch?v=NKHi12DMcC4

                                               title               category  \
0  Creative Flower Photography with Phone📱 🔥| Pho...  photography tutorials
1  How to Learn The Basics of Christianity Withou...      religious content
2                           Travel Photography Tip 📲  photography tutorials
3  Travel with me✈️! #travel #facemask #vlog #mak...             travelling
4  How to survive college #cooking #food #foodasm...           food recipes

   duration_seconds  view_count  like_count  comment_count
0                13      620112       14371             54
1                20      361355       17500            783
2                43    40748489     2903165          12652
3                36     4904533      101047            580
4                38     7665699           0           1422

In [29]:
df2 = df2[df1.columns]


print(df2.columns)

Index(['url', 'title', 'category', 'duration_seconds', 'view_count',
       'like_count', 'comment_count'],
      dtype='object')

In [31]:
df = pd.concat([df1, df2], ignore_index=True)

print(df['duration_seconds'].max())

57468

In [32]:

df = df.sort_values(by='url', ascending=False)
df = df.drop_duplicates(subset='title', keep='first').reset_index(drop=True)

In [33]:
df.head(10)

,url,title,category,duration_seconds,view_count,like_count,comment_count
0,https://www.youtube.com/watch?v=zuiU_mD-p0c,This ONE Bible Verse Boosted My Faith #Shorts,religious content,55,1097261,165069,45568
1,https://www.youtube.com/watch?v=ztFAl1To3Wo,Ever tried Crispy Banana Bonda 🤤#shorts,food recipes,52,95273478,1468403,6862
2,https://www.youtube.com/watch?v=zpQ_jC57W4E,Camera Flash tip for beginners - Godox v1 lamp...,photography tutorials,23,479077,9712,92
3,https://www.youtube.com/watch?v=zlomFl0KSVQ,Extend Background Photo - Short Photoshop Tuto...,photography tutorials,31,198509,7118,24
4,https://www.youtube.com/watch?v=zcTCJCLCKEA,Grand Celebration of the Twins with Special Pe...,vlogs,838,4989,238,17
5,https://www.youtube.com/watch?v=z_DgvMHnfjc,My go to settings for sports photography in ma...,photography tutorials,14,2327745,95924,583
6,https://www.youtube.com/watch?v=zY6MHzF8ZN0,Just winter things 🥹 #relatable #funny #indian...,funny content,10,15208708,373311,495
7,https://www.youtube.com/watch?v=zR_IarVr2AI,Places In Real Life #travel #explore #adventur...,travelling,16,206057629,6853449,8625
8,https://www.youtube.com/watch?v=zKCCTN736Bs,#vlog | Saturday Vachindante Apudapudu Inthe 😡...,vlogs,1753,37413,808,146
9,https://www.youtube.com/watch?v=zIbCVHDBqOI,Episode -1 About lens focusing AF & MF | Telug...,photography tutorials,60,176802,14646,62

In [34]:
df['title'].duplicated().sum()

np.int64(0)

In [35]:
df.isna().sum()

url                 0
title               0
category            0
duration_seconds    0
view_count          0
like_count          0
comment_count       0
dtype: int64

In [36]:
df.info

<bound method DataFrame.info of                                               url  \
0     https://www.youtube.com/watch?v=zuiU_mD-p0c
1     https://www.youtube.com/watch?v=ztFAl1To3Wo
2     https://www.youtube.com/watch?v=zpQ_jC57W4E
3     https://www.youtube.com/watch?v=zlomFl0KSVQ
4     https://www.youtube.com/watch?v=zcTCJCLCKEA
...                                           ...
1790  https://www.youtube.com/watch?v=-3bG5bzUKmI
1791  https://www.youtube.com/watch?v=-3Tc6b74TXE
1792  https://www.youtube.com/watch?v=-30pyWb7mxs
1793  https://www.youtube.com/watch?v=-2KIoyDX8Dc
1794  https://www.youtube.com/watch?v=-0-U20gTt38

                                                  title  \
0         This ONE Bible Verse Boosted My Faith #Shorts
1               Ever tried Crispy Banana Bonda 🤤#shorts
2     Camera Flash tip for beginners - Godox v1 lamp...
3     Extend Background Photo - Short Photoshop Tuto...
4     Grand Celebration of the Twins with Special Pe...
...                                                 ...
1790  Instant Crispy Potato Triangles Recipe | Party...
1791         Singapore ki jeans😂 #shorts #funny #comedy
1792  The male need and urge for FREE #warframe #gam...
1793  Steal our UDAIPUR Travel Guide ✨💕 #udaipur #tr...
1794  How to do Light Painting Photography using the...

                   category  duration_seconds  view_count  like_count  \
0         religious content                55     1097261      165069
1              food recipes                52    95273478     1468403
2     photography tutorials                23      479077        9712
3     photography tutorials                31      198509        7118
4                     vlogs               838        4989         238
...                     ...               ...         ...         ...
1790           food recipes                21    13172670      195142
1791          funny content                60     6596645      192107
1792                 gaming                60      150360        9998
1793             travelling                59     1538968       52389
1794  photography tutorials                18      536591       18975

      comment_count
0             45568
1              6862
2                92
3                24
4                17
...             ...
1790            485
1791            152
1792            192
1793            174
1794             83

[1795 rows x 7 columns]>

In [22]:
print(df['duration_seconds'].max())

57468

In [38]:
df.to_csv('Final Data integraated.csv', index=False)


print("Integrated dataset saved to 'Final Data integraation.csv'")

Integrated dataset saved to 'Final Data integraation.csv'